// Types for AgriAuct

export type UserRole = "farmer" | "vendor"

export interface User {
  id: string
  fullName: string
  email: string
  phone: string
  state: string
  district: string
  role: UserRole
  createdAt: Date
}

export type Category = "vegetables" | "fruits" | "grains" | "other"
export type QualityGrade = "A" | "B" | "C"
export type ListingStatus = "active" | "closed"

export interface Listing {
  id: string
  farmerId: string
  farmerName: string
  cropName: string
  category: Category
  quantity: number
  qualityGrade: QualityGrade
  state: string
  district: string
  startingPrice: number
  currentHighestBid: number
  auctionDuration: number
  startTime: Date
  endTime: Date
  status: ListingStatus
  imageUrl: string
  bidCount: number
  winnerId?: string
  winnerName?: string
}

export interface Bid {
  id: string
  listingId: string
  vendorId: string
  vendorName: string
  amount: number
  createdAt: Date
}

export interface Notification {
  id: string
  userId: string
  message: string
  isRead: boolean
  createdAt: Date
  type: "outbid" | "won" | "auction_ended" | "new_bid"
  listingId?: string
}

// Indian states, union territories and their districts
// Source: Government of India / Census & administrative listings (consolidated)
export const indianStateDistricts: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Alluri Sitharama Raju",
    "Anakapalli",
    "Anantapur",
    "Annamayya",
    "Bapatla",
    "Chittoor",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Kakinada",
    "Konaseema",
    "Krishna",
    "Kurnool",
    "Nandyal",
    "NTR",
    "Palnadu",
    "Parvathipuram Manyam",
    "Prakasam",
    "Srikakulam",
    "Sri Potti Sriramulu Nellore",
    "Sri Sathya Sai",
    "Tirupati",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR"
  ],
  "Arunachal Pradesh": [
    "Anjaw",
    "Changlang",
    "Dibang Valley",
    "East Kameng",
    "East Siang",
    "Kamle",
    "Kra Daadi",
    "Kurung Kumey",
    "Lepa Rada",
    "Lohit",
    "Longding",
    "Lower Dibang Valley",
    "Lower Siang",
    "Lower Subansiri",
    "Namsai",
    "Pakke Kessang",
    "Papum Pare",
    "Shi Yomi",
    "Siang",
    "Tawang",
    "Tirap",
    "Upper Dibang Valley",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang"
  ],
  Assam: [
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong"
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran"
  ],
  Chhattisgarh: [
    "Balod",
    "Baloda Bazar",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada",
    "Dhamtari",
    "Durg",
    "Gariaband",
    "Gaurela Pendra Marwahi",
    "Janjgir Champa",
    "Jashpur",
    "Kabirdham",
    "Kanker",
    "Kondagaon",
    "Korba",
    "Koriya",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sukma",
    "Surajpur",
    "Surguja"
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Devbhoomi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kheda",
    "Kutch",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahal",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad"
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar"
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una"
  ],
  Jharkhand: [
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Saraikela Kharsawan",
    "Simdega",
    "West Singhbhum"
  ],
  Karnataka: [
    "Bagalkote",
    "Ballari",
    "Belagavi",
    "Bengaluru Rural",
    "Bengaluru Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikballapur",
    "Chikkamagaluru",
    "Chitradurga",
    "Dakshina Kannada",
    "Davangere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalaburagi",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysuru",
    "Raichur",
    "Ramanagara",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Uttara Kannada",
    "Vijayapura",
    "Yadgir"
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad"
  ],
  "Madhya Pradesh": [
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha"
  ],
  Maharashtra: [
    "Ahilyanagar",
    "Akola",
    "Amravati",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Chhatrapati Sambhajinagar",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal"
  ],
  Manipur: [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kakching",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul"
  ],
  Meghalaya: [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "North Garo Hills",
    "Ri-Bhoi",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills"
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Hnahthial",
    "Khawzawl",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Saitual",
    "Serchhip"
  ],
  Nagaland: [
    "Chumoukedima",
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Niuland",
    "Noklak",
    "Peren",
    "Phek",
    "Shamator",
    "Tseminyu",
    "Tuensang",
    "Wokha",
    "Zunheboto"
  ],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Bhadrak",
    "Boudh",
    "Cuttack",
    "Deogarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar",
    "Khordha",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Subarnapur",
    "Sundargarh"
  ],
  Punjab: [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Mansa",
    "Moga",
    "Mohali",
    "Muktsar",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar",
    "Tarn Taran"
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Dungarpur",
    "Ganganagar",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Tonk",
    "Udaipur"
  ],
  Sikkim: ["Gangtok", "Mangan", "Namchi", "Pakyong", "Soreng", "Gyalshing"],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"
  ],
  Telangana: [
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hanumakonda",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhupalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Komaram Bheem Asifabad",
    "Mahabubabad",
    "Mahabubnagar",
    "Mancherial",
    "Medak",
    "Medchal Malkajgiri",
    "Mulugu",
    "Nagarkurnool",
    "Nalgonda",
    "Nirmal",
    "Nizamabad",
    "Peddapalli",
    "Rajanna Sircilla",
    "Ranga Reddy",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal",
    "Yadadri Bhuvanagiri"
  ],
  Tripura: [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "Unakoti",
    "West Tripura"
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi"
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kheri",
    "Kushinagar",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi"
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur"
  ],
  "Andaman and Nicobar Islands": [
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman"
  ],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Dadra and Nagar Haveli",
    "Daman",
    "Diu"
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi"
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur"
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"]
}

export const indianStates = Object.keys(indianStateDistricts)

export const categories: { value: Category; label: string }[] = [
  { value: "vegetables", label: "Vegetables" },
  { value: "fruits", label: "Fruits" },
  { value: "grains", label: "Grains" },
  { value: "other", label: "Other" },
]

export const qualityGrades: { value: QualityGrade; label: string }[] = [
  { value: "A", label: "Grade A - Premium" },
  { value: "B", label: "Grade B - Standard" },
  { value: "C", label: "Grade C - Economy" },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: "farmer-1",
    fullName: "Rajesh Kumar",
    email: "rajesh@example.com",
    phone: "+91 98765 43210",
    state: "Punjab",
    district: "Ludhiana",
    role: "farmer",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "farmer-2",
    fullName: "Priya Sharma",
    email: "priya@example.com",
    phone: "+91 98765 43211",
    state: "Maharashtra",
    district: "Nashik",
    role: "farmer",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "vendor-1",
    fullName: "Amit Patel",
    email: "amit@example.com",
    phone: "+91 98765 43212",
    state: "Gujarat",
    district: "Ahmedabad",
    role: "vendor",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "vendor-2",
    fullName: "Sunita Reddy",
    email: "sunita@example.com",
    phone: "+91 98765 43213",
    state: "Telangana",
    district: "Hyderabad",
    role: "vendor",
    createdAt: new Date("2024-02-25"),
  },
]

// Helper to create dates relative to now
const hoursFromNow = (hours: number) => new Date(Date.now() + hours * 60 * 60 * 1000)
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000)

// Mock Listings
export const mockListings: Listing[] = [
  {
    id: "listing-1",
    farmerId: "farmer-1",
    farmerName: "Rajesh Kumar",
    cropName: "Organic Wheat",
    category: "grains",
    quantity: 500,
    qualityGrade: "A",
    state: "Punjab",
    district: "Ludhiana",
    startingPrice: 2500,
    currentHighestBid: 3200,
    auctionDuration: 24,
    startTime: hoursAgo(12),
    endTime: hoursFromNow(12),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop",
    bidCount: 8,
  },
  {
    id: "listing-2",
    farmerId: "farmer-1",
    farmerName: "Rajesh Kumar",
    cropName: "Fresh Tomatoes",
    category: "vegetables",
    quantity: 200,
    qualityGrade: "A",
    state: "Punjab",
    district: "Ludhiana",
    startingPrice: 1500,
    currentHighestBid: 2100,
    auctionDuration: 12,
    startTime: hoursAgo(6),
    endTime: hoursFromNow(6),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1546470427-227c7b3f8968?w=400&h=300&fit=crop",
    bidCount: 5,
  },
  {
    id: "listing-3",
    farmerId: "farmer-2",
    farmerName: "Priya Sharma",
    cropName: "Alphonso Mangoes",
    category: "fruits",
    quantity: 100,
    qualityGrade: "A",
    state: "Maharashtra",
    district: "Nashik",
    startingPrice: 5000,
    currentHighestBid: 7500,
    auctionDuration: 48,
    startTime: hoursAgo(24),
    endTime: hoursFromNow(24),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop",
    bidCount: 12,
  },
  {
    id: "listing-4",
    farmerId: "farmer-2",
    farmerName: "Priya Sharma",
    cropName: "Onions",
    category: "vegetables",
    quantity: 300,
    qualityGrade: "B",
    state: "Maharashtra",
    district: "Nashik",
    startingPrice: 1000,
    currentHighestBid: 1450,
    auctionDuration: 8,
    startTime: hoursAgo(4),
    endTime: hoursFromNow(4),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07c93a8e8f1?w=400&h=300&fit=crop",
    bidCount: 4,
  },
  {
    id: "listing-5",
    farmerId: "farmer-1",
    farmerName: "Rajesh Kumar",
    cropName: "Basmati Rice",
    category: "grains",
    quantity: 1000,
    qualityGrade: "A",
    state: "Punjab",
    district: "Ludhiana",
    startingPrice: 8000,
    currentHighestBid: 12500,
    auctionDuration: 24,
    startTime: hoursAgo(30),
    endTime: hoursAgo(6),
    status: "closed",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop",
    bidCount: 15,
    winnerId: "vendor-1",
    winnerName: "Amit Patel",
  },
  {
    id: "listing-6",
    farmerId: "farmer-2",
    farmerName: "Priya Sharma",
    cropName: "Green Grapes",
    category: "fruits",
    quantity: 150,
    qualityGrade: "A",
    state: "Maharashtra",
    district: "Nashik",
    startingPrice: 3000,
    currentHighestBid: 4200,
    auctionDuration: 12,
    startTime: hoursAgo(18),
    endTime: hoursAgo(6),
    status: "closed",
    imageUrl: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=300&fit=crop",
    bidCount: 9,
    winnerId: "vendor-2",
    winnerName: "Sunita Reddy",
  },
  {
    id: "listing-7",
    farmerId: "farmer-1",
    farmerName: "Rajesh Kumar",
    cropName: "Potatoes",
    category: "vegetables",
    quantity: 400,
    qualityGrade: "B",
    state: "Punjab",
    district: "Ludhiana",
    startingPrice: 1200,
    currentHighestBid: 1800,
    auctionDuration: 16,
    startTime: hoursAgo(8),
    endTime: hoursFromNow(8),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82ber3a8?w=400&h=300&fit=crop",
    bidCount: 6,
  },
  {
    id: "listing-8",
    farmerId: "farmer-2",
    farmerName: "Priya Sharma",
    cropName: "Sugarcane",
    category: "other",
    quantity: 800,
    qualityGrade: "A",
    state: "Maharashtra",
    district: "Nashik",
    startingPrice: 4000,
    currentHighestBid: 5500,
    auctionDuration: 36,
    startTime: hoursAgo(12),
    endTime: hoursFromNow(24),
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1527847263472-aa5338d178b8?w=400&h=300&fit=crop",
    bidCount: 7,
  },
]

// Mock Bids
export const mockBids: Bid[] = [
  {
    id: "bid-1",
    listingId: "listing-1",
    vendorId: "vendor-1",
    vendorName: "Amit Patel",
    amount: 2800,
    createdAt: hoursAgo(10),
  },
  {
    id: "bid-2",
    listingId: "listing-1",
    vendorId: "vendor-2",
    vendorName: "Sunita Reddy",
    amount: 3000,
    createdAt: hoursAgo(8),
  },
  {
    id: "bid-3",
    listingId: "listing-1",
    vendorId: "vendor-1",
    vendorName: "Amit Patel",
    amount: 3200,
    createdAt: hoursAgo(4),
  },
  {
    id: "bid-4",
    listingId: "listing-2",
    vendorId: "vendor-2",
    vendorName: "Sunita Reddy",
    amount: 1800,
    createdAt: hoursAgo(4),
  },
  {
    id: "bid-5",
    listingId: "listing-2",
    vendorId: "vendor-1",
    vendorName: "Amit Patel",
    amount: 2100,
    createdAt: hoursAgo(2),
  },
  {
    id: "bid-6",
    listingId: "listing-3",
    vendorId: "vendor-1",
    vendorName: "Amit Patel",
    amount: 6000,
    createdAt: hoursAgo(20),
  },
  {
    id: "bid-7",
    listingId: "listing-3",
    vendorId: "vendor-2",
    vendorName: "Sunita Reddy",
    amount: 6500,
    createdAt: hoursAgo(16),
  },
  {
    id: "bid-8",
    listingId: "listing-3",
    vendorId: "vendor-1",
    vendorName: "Amit Patel",
    amount: 7000,
    createdAt: hoursAgo(10),
  },
  {
    id: "bid-9",
    listingId: "listing-3",
    vendorId: "vendor-2",
    vendorName: "Sunita Reddy",
    amount: 7500,
    createdAt: hoursAgo(5),
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "vendor-1",
    message: "You were outbid on Alphonso Mangoes. Current highest bid is ₹7,500",
    isRead: false,
    createdAt: hoursAgo(5),
    type: "outbid",
    listingId: "listing-3",
  },
  {
    id: "notif-2",
    userId: "vendor-1",
    message: "Congratulations! You won the auction for Basmati Rice at ₹12,500",
    isRead: true,
    createdAt: hoursAgo(6),
    type: "won",
    listingId: "listing-5",
  },
  {
    id: "notif-3",
    userId: "vendor-2",
    message: "Congratulations! You won the auction for Green Grapes at ₹4,200",
    isRead: true,
    createdAt: hoursAgo(6),
    type: "won",
    listingId: "listing-6",
  },
  {
    id: "notif-4",
    userId: "farmer-1",
    message: "New bid received on Organic Wheat: ₹3,200",
    isRead: false,
    createdAt: hoursAgo(4),
    type: "new_bid",
    listingId: "listing-1",
  },
  {
    id: "notif-5",
    userId: "farmer-1",
    message: "Your auction for Basmati Rice has ended. Winner: Amit Patel",
    isRead: true,
    createdAt: hoursAgo(6),
    type: "auction_ended",
    listingId: "listing-5",
  },
]

// Helper functions
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatTimeRemaining(endTime: Date): string {
  const now = new Date()
  const diff = endTime.getTime() - now.getTime()

  if (diff <= 0) return "Ended"

  const hours = Math.floor(diff / (1000 * 60 * 60))
  const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60))
  const seconds = Math.floor((diff % (1000 * 60)) / 1000)

  if (hours > 24) {
    const days = Math.floor(hours / 24)
    return `${days}d ${hours % 24}h`
  }

  if (hours > 0) {
    return `${hours}h ${minutes}m`
  }

  return `${minutes}m ${seconds}s`
}

export function getTimeRemainingMs(endTime: Date): number {
  return Math.max(0, endTime.getTime() - Date.now())
}

export function getCategoryLabel(category: Category): string {
  return categories.find((c) => c.value === category)?.label || category
}

export function getQualityLabel(grade: QualityGrade): string {
  return `Grade ${grade}`
}
